version: "3"
services:
  web:
    build: .
    command: ["uvicorn", "main.application:app", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - "6576:80"
    env_file:
      - .env
    restart: always
